---
engines:
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
  vint:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.vim"
exclude_paths: []
