kind: pipeline
type: docker
name: test

steps:
  - name: Test Python
    image: python:3.9
    privileged: true
    commands:
      - pip install flake8
      - flake8 --exclude files/vim

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - apk add --no-cache bash git
      - scripts/test_bash.sh
