kind: pipeline
type: docker
name: test

steps:
  - name: Test Python
    image: python:3.14
    commands:
      - pip install ruff
      - ruff check . --exclude files/vim,scripts/git/req-update --select E,F,W,A,B,COM,N,PLC,PLE,PLW

  - name: Test Vim
    image: python:3.14
    commands:
      - pip install vim-vint==0.3.21 setuptools==81.0.0
      - git ls-files | grep vim | grep -v sh.vim | grep -v pack | grep -v spell | xargs vint

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - apk add --no-cache bash git
      - scripts/test_bash.sh
