kind: pipeline
type: docker
name: test

steps:
  - name: Test Python
    image: python:3.9
    commands:
      - pip install flake8
      - flake8 --exclude files/vim

  - name: Test
    image: ubuntu:20.04
    commands:
      - scripts/test_setup.sh
      - scripts/test.sh
