#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

gitlocation=${GIT_PREFIX:-./}
search="${1:-}"
location="${2:-./}"

if [ -z "$search" ]; then
    echo "Find files matching a grep"
    echo "Usage: git find \$searchterm [\$location]"
    exit 1
fi

cd "$gitlocation"

deleted="$(git ls-files -d "$location" | grep "$search")"
found="$(git ls-files "$location" | grep "$search")"

echo "$found" | grep -Fv "$deleted"
