#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

location=${GIT_PREFIX:-./}
search="${1:-}"
if [ -z "$search" ]; then
    echo "Delete lines in version controlled files that contain a string"
    echo "Usage: git finddelete \$searchterm"
    exit 1
fi
escaped_search=$(printf '%s\n' "$search" | sed -e 's/[]\/$*.^[]/\\&/g');

sed2() {
    file="$1"
    echo "$file"
    if [[ $(uname) == Darwin ]]; then
        sed -i '' -e "/$escaped_search/d" "$file"
    else
        sed -i -e "/$escaped_search/d" "$file"
    fi
}

files="$(git grep -l "$search" "$location")"
pids=();
for file in $files; do
    sed2 "$file" &
    pids+=($!)
done

for pid in "${pids[@]}"; do
    wait "$pid"
done
