#!/bin/bash

set -e

location=${GIT_PREFIX:-./}

git ls-files --stage "$location" \
    | grep 100 \
    | cut -f2 \
    | xargs file \
    | awk -F: '/ASCII text/ {print $1    }' \
    | xargs -t -L 1 sed -i -e "s/$1/$2/g";
