#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

location=${GIT_PREFIX:-./}
FIND="$1"
ESCAPED_FIND=$(printf '%s\n' "$FIND" | sed -e 's/[]\/$*.^[]/\\&/g');
REPLACE="$2"
ESCAPED_REPLACE=$(printf '%s\n' "$REPLACE" | sed -e 's/[]\/$*.^[]/\\&/g');

sed2() {
    FILE="$1"

    if [ -z "$(file "$FILE" | grep text)" ]; then
        return
    fi
    echo "$FILE"
    if [[ $(uname) == Darwin ]]; then
        sed -i '' -e "s/$ESCAPED_FIND/$ESCAPED_REPLACE/g" "$FILE"
    else
        sed -i -e "s/$ESCAPED_FIND/$ESCAPED_REPLACE/g" "$FILE"
    fi
}

files="$(git ls-files --stage "$location" \
    | grep 100 \
    | cut -f2
)"

for file in $files; do
    sed2 "$file"
done
