#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

location=${GIT_PREFIX:-./}
FIND="$1"
ESCAPED_FIND=$(printf '%s\n' "$FIND" | sed -e 's/[]\/$*.^[]/\\&/g');
REPLACE="$2"
ESCAPED_REPLACE=$(printf '%s\n' "$REPLACE" | sed -e 's/[]\/$*.^[]/\\&/g');

sed2() {
    if [[ $(uname) == Darwin ]]; then
        sed -i '' -e "s/$ESCAPED_FIND/$ESCAPED_REPLACE/g" "$3"
    else
        sed -i -e "s/$ESCAPED_FIND/$ESCAPED_REPLACE/g" "$3"
    fi
}

files="$(git ls-files --stage "$location" \
    | grep 100 \
    | cut -f2 \
    | xargs file \
    | awk -F: '/text/ {print $1    }')"

for file in $files; do
    sed2 "$1" "$2" "$file"
done
