#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

echo "Users by commits"
git shortlog -sne | \
    head -n 20

echo ""
echo "Users by line changes"
git ls-files | \
    xargs -n1 git blame --line-porcelain 2> /dev/null | \
    sed -n 's/^author //p' | \
    sort -f | \
    uniq -ic | \
    sort -nr | \
    head -n 20
