steps:
  - command: "cp -r /workdir-original /workdir && /workdir/scripts/test.sh"
    label: "Test"
    key: "test"
    plugins:
      - docker#v3.7.0:
          image: "ubuntu:20.04"
          propagate-environment: true
          mount-buildkite-agent: false
          mount-checkout: false
          volumes: [".:/workdir-original"]
          workdir: ["/workdir"]
