Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "REPLACEME.local"
  config.vm.network :private_network, ip: "192.168.56.102REPLACEME"
  config.vm.network :forwarded_port, guest: 22, host: 2200REPLACEME, id: 'ssh'

  config.ssh.forward_agent = true
  config.ssh.port = 2200REPLACEME
  config.ssh.guest_port = 22

  config.vm.provider :virtualbox do |vb|
    vb.name = "REPLACEME"
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["storageattach", :id, "--storagectl", "SATAController",
      "--port", "0", "--nonrotational", "on"]
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end
end
