#!/bin/bash

# Homebrew
if hash brew 2>/dev/null; then
    brewprefix=$(brew --prefix)
    export PATH="$brewprefix/sbin:$brewprefix/bin:$PATH:$HOME/bin"
    export HOMEBREW_NO_SANDBOX=1
    if [ -s "$brewprefix/etc/bash_completion" ]; then
        . "$brewprefix/etc/bash_completion"
    fi
fi

[[ -r $HOME/.bashrc ]] && . ~/.bashrc
