#!/bin/bash

### Setting variables
export EDITOR=vim
export LANG="en_US"
export LC_ALL=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
export HISTCONTROL=ignorespace
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export GOPATH=$HOME/gocode
export VIRTUALENVWRAPPER_PYTHON="$(command \which python3)"

# Set bash prompt
blue='\[\e[1;34m\]'
red='\[\e[1;31m\]'
yellow='\[\e[1;33m\]'
magentabackground='\[\e[1;45m\]'
reset='\[\e[0m\]'
if [[ "$(hostname)" == *"personal"* ]] || [[ "$(uname)" == "Darwin" ]]; then
    PS1="$blue\u$red@\[$yellow\h$red \w \$ $reset"
else
    PS1="$blue\u$red@\[$yellow$magentabackground\h$reset$red \w \$ $reset"
fi

### Assorted aliases
function path() { echo "$PATH" | tr ':' '\n'; }
alias grep='grep --color=auto'
alias oports="echo 'User:      Command:   Port:'; echo '----------------------------' ; lsof -i 4 -P -n | grep -i 'listen' | awk '{print \$3, \$1, \$9}' | sed 's/ [a-z0-9\.\*]*:/ /' | sort -k 3 -n |xargs printf '%-10s %-10s %-10s\n' | uniq"
alias mem="ps aux | sed -n 1p && ps aux | sort -b -k 4 | tail -n 30"
alias cpu="ps aux | sed -n 1p && ps aux | sort -b -k 3 | tail -n 30"
alias sudo='sudo '
alias fucking='sudo'
alias hardware='hardware.sh'
alias scp="rsync"
alias rsync='rsync -vazhP'
alias alert='echo -e "\a"'
alias diff='icdiff'
alias tree='tree -C'
alias du='du -h'
alias mkdir='mkdir -p'
alias myip='curl --silent ipinfo.io | jq -r .ip'
function geoip { curl "ipinfo.io/$1"; }
export -f geoip
alias rspec='xvfb-run -a bundle exec rspec'
if [[ $(uname) == Linux ]]; then
    alias ls='ls --color=always'
fi
alias serve="python3 -m http.server"
alias realpath='python -c "import os, sys; print(os.path.realpath(sys.argv[1]))"'
alias gosymlink="cd $(realpath .)"
alias portgrep="sudo ngrep -d any port"
alias apt-get="apt"
if [[ $(uname) == Linux ]]; then
    alias portlist="sudo netstat -lntup"
elif [[ $(uname) == Darwin ]]; then
    alias portlist="sudo lsof -i -P | grep -i 'listen'"
    if [ -f /usr/local/bin/vim ]; then
        alias vi=/usr/local/bin/vim
    fi
fi

### Sourcing other scripts
source "$HOME/.dotfiles/files/completion/git-completion.sh"
source "$HOME/.dotfiles/files/completion/rake-completion.sh"
source "$HOME/.dotfiles/files/completion/django-completion.sh"

### Adjusting the PATH
export PATH="$PATH:$HOME/.dotfiles/bin"
export PATH="$PATH:/usr/local/heroku/bin"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.rvm/bin"                    # Add RVM to PATH for scripting
export PATH="/usr/local/opt/python/libexec/bin:$PATH" # Read brew python, needed for virtualenvwrapper

# Node
export PATH="$PATH:node_modules/.bin"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
source "$HOME/.dotfiles/files/completion/npm-completion.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[[ -r $HOME/.bashrc_local ]] && . ~/.bashrc_local

### Git updates
~/.dotfiles/scripts/chmod-private-keys.sh
~/.dotfiles/scripts/update-dotfiles.sh &
disown
