#!/bin/bash

if [ "$(uname)" == "Darwin" ]; then
    # Remove mac terminal notification about zsh
    export BASH_SILENCE_DEPRECATION_WARNING=1

    # Homebrew
    eval "$(/opt/homebrew/bin/brew shellenv)"
    brewprefix=$(brew --prefix)
    if [ -s "$brewprefix/etc/bash_completion.d/brew" ]; then
        . "$brewprefix/etc/bash_completion.d/brew"
    fi
fi

[[ -r $HOME/.bashrc ]] && . ~/.bashrc
