#!/bin/bash

# Homebrew
if hash brew 2>/dev/null; then
    export PATH=$(brew --prefix)/sbin:$(brew --prefix)/bin:$PATH:$HOME/bin
    export HOMEBREW_NO_SANDBOX=1
fi

[[ -r $HOME/.bashrc ]] && . ~/.bashrc

type "brew" &>/dev/null && [ -s "$(brew --prefix)/etc/bash_completion" ] && . $(brew --prefix)/etc/bash_completion
