#!/usr/bin/env bash

export GOPATH=$HOME/Uber/gocode
export PATH="$PATH:$GOPATH/bin"
export UBER_HOME="$HOME/Uber"
export UBER_OWNER="albertyw@uber.com"
export UBER_LDAP_UID="albertyw"

alias ussh="ussh && ~/.dotfiles/npm_reset"

unset ANTHROPIC_AUTH_TOKEN
unset ANTHROPIC_BASE_URL

# Uber web monorepo
# export PATH="/opt/homebrew/opt/node@22/bin:$PATH"

# Uber adds a bunch of crap to the hostname, override it
blue='\[\e[1;34m\]'
red='\[\e[1;31m\]'
yellow='\[\e[1;33m\]'
reset='\[\e[0m\]'
PS1="${blue}\u${red}@\[${yellow}albertyw${red} \w \$ ${reset}"

# Uber
[ -r ~/.profile_lda ] && . ~/.profile_lda
