#!/bin/bash

### Adjusting the PATH
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH="node_modules/.bin:$PATH"

### Setting variables
export EDITOR=vim
export LANG="en_US"
export LC_ALL=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
export HISTCONTROL=ignorespace
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export GOPATH=$HOME/gocode
export PATH=$GOPATH/bin:$PATH

# Set bash prompt
blue='\[\e[1;34m\]'
red='\[\e[1;31m\]'
yellow='\[\e[1;33m\]'
magentabackground='\[\e[1;45m\]'
reset='\[\e[0m\]'
if [[ "$(hostname)" == *"personal"* ]] || [[ "$(uname)" == "Darwin" ]]; then
    PS1="$blue\u$red@\[$yellow\h$red \w \$ $reset"
else
    PS1="$blue\u$red@\[$yellow$magentabackground\h$reset$red \w \$ $reset"
fi

### Assorted aliases
function path() { echo $PATH | tr ':' '\n'; }
alias grep='grep --color=auto'
alias oports="echo 'User:      Command:   Port:'; echo '----------------------------' ; lsof -i 4 -P -n | grep -i 'listen' | awk '{print \$3, \$1, \$9}' | sed 's/ [a-z0-9\.\*]*:/ /' | sort -k 3 -n |xargs printf '%-10s %-10s %-10s\n' | uniq"
alias mem="ps aux | sed -n 1p && ps aux | sort -b -k 4 | tail -n 30"
alias cpu="ps aux | sed -n 1p && ps aux | sort -b -k 3 | tail -n 30"
alias fucking='sudo'
alias lookup='$HOME/.dotfiles/bin/lookup.sh'
alias hardware='hardware.sh'
alias scp="rsync"
alias rsync='rsync -vazhP'
alias alert='echo -e "\a"'
alias diff='icdiff'
alias tree='tree -C'
alias du='du -h'
alias mkdir='mkdir -p'
function geoip { curl "ipinfo.io/$1"; }
export -f geoip
alias rspec='xvfb-run -a bundle exec rspec'
if [[ $(uname) == Linux ]]; then
    alias ls='ls --color=always'
fi
alias serve="python -m SimpleHTTPServer"
alias gosymlink="cd -P \`pwd\`"
alias portgrep="sudo ngrep -d any port"
if [[ $(uname) == Linux ]]; then
    alias portlist="sudo netstat -lntup"
elif [[ $(uname) == Darwin ]]; then
    alias portlist="sudo lsof -i -P | grep -i 'listen'"
fi

### Sourcing other scripts
source $HOME/.dotfiles/files/completion/git-completion.sh
source $HOME/.dotfiles/files/completion/npm-completion.sh
source $HOME/.dotfiles/files/completion/rake-completion.sh
source $HOME/.dotfiles/files/completion/django-completion.sh
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/heroku/bin:$PATH"

[[ -r $HOME/.bashrc_local ]] && . ~/.bashrc_local

### Git updates
~/.dotfiles/scripts/chmod-private-keys.sh
~/.dotfiles/scripts/update-dotfiles.sh &
disown
