" settings for vim
call pathogen#infect()

syntax on
set background=dark
set ruler
set nowrap
set number
set enc=utf-8

" Highlight current line
set cursorline
hi CursorLine cterm=NONE ctermbg=DarkBlue

" Show invisible characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

if has("terminfo")
  let &t_Co=8
  let &t_Sf="\e[3%p1%dm"
  let &t_Sb="\e[4%p1%dm"
else
  let &t_Co=8
  let &t_Sf="\e[3%dm"
  let &t_Sb="\e[4%dm"
endif

au BufRead,BufNewFile *.dj setfiletype htmldjango
au BufRead,BufNewFile *.hamlc set ft=haml

set hlsearch
set modeline

set expandtab
set tabstop=4
set autoindent
set shiftwidth=4
set noerrorbells

filetype on
filetype plugin indent on
