filetype on
filetype plugin indent on

syntax on
set background=dark
set ruler
set nowrap
set number
set backspace=indent,eol,start
set encoding=utf-8
scriptencoding utf-8

" Highlight current line
set cursorline
hi CursorLine cterm=NONE ctermbg=DarkBlue

" Show invisible characters
set lcs=tab:▸\ ,trail:·,nbsp:_
set list

if has('terminfo')
  let &t_Co=8
  let &t_Sf="\e[3%p1%dm"
  let &t_Sb="\e[4%p1%dm"
else
  let &t_Co=8
  let &t_Sf="\e[3%dm"
  let &t_Sb="\e[4%dm"
endif

" Disable gopls code because Uber's Go Monorepo is slow
let g:go_gopls_enabled = 0

augroup filetypes
    au BufNewFile,BufRead requirements-*.txt set ft=requirements
    au BufRead,BufNewFile *.dj setfiletype htmldjango
    au BufRead,BufNewFile .env* set syntax=sh
    au BufRead,BufNewFile Dockerfile* set syntax=dockerfile

    autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
    autocmd Filetype typescript setlocal ts=2 sts=2 sw=2
    autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
augroup END

set hlsearch
set modeline

set expandtab
set tabstop=4
set autoindent
set shiftwidth=4
set noerrorbells

" Disable folding
set nofoldenable
