filetype on
filetype plugin indent on

syntax on
set background=dark
set ruler
set nowrap
set number
set backspace=indent,eol,start
set encoding=utf-8
scriptencoding utf-8
try
    colorscheme albertyw
    colorscheme vim
catch /^Vim\%((\a\+)\)\=:E185/
    " deal with it
endtry

" Show invisible characters
set lcs=tab:▸\ ,trail:·,nbsp:_
set list

augroup filetypes
    au BufNewFile,BufRead requirements-*.txt set ft=requirements
    au BufRead,BufNewFile *.dj setfiletype htmldjango
    au BufRead,BufNewFile .env* set syntax=sh
    au BufRead,BufNewFile Dockerfile* set syntax=dockerfile
    au BufRead,BufNewFile METADATA set syntax=yaml
    au BufRead,BufNewFile *.conf set syntax=dosini

    autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
    autocmd Filetype css setlocal ts=2 sts=2 sw=2
    autocmd Filetype scss setlocal ts=2 sts=2 sw=2
    autocmd Filetype typescript setlocal ts=2 sts=2 sw=2
    autocmd Filetype typescriptreact setlocal ts=2 sts=2 sw=2
    autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

    au BufRead,BufNewFile go.mod set syntax=gomod
    au BufRead,BufNewFile go.sum set syntax=gosum
augroup END

augroup WrapLineInTeXFile
    autocmd!
    autocmd FileType markdown setlocal wrap
augroup END

set hlsearch
set modeline

set expandtab
set tabstop=4
set autoindent
set shiftwidth=4
set noerrorbells

" Disable folding
set nofoldenable

imap <silent><script><expr> <C-space> copilot#Accept("\<CR>")
let g:copilot_no_tab_map = v:true
