#!/bin/bash


if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
  # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

IFS=$'\n' # Only split on newlines, not spaces
for f in $(exec git diff-index --cached --check $against -- | sed '/^[-+]/d' | cut -d: -f1 | uniq) ; do

    # Remove trailing whitespace
    echo "* Removed whitespace: $f"
    if [[ $(uname) == Darwin ]]; then
        sed -i '' -E 's/[[:space:]]*$//' "$f"
    else
        sed -i 's/[[:space:]]*$//' "$f"
    fi
    git add "$f"
done

files=$(git diff-index --name-status --cached HEAD | grep -v ^D | cut -c3-)
for f in $files
do
    # Add linebreak to end of file if it doesn't have one
    if [ "$(tail -c 1 "$f")" != "" ]
    then
        echo >> "$f"
    fi
    git add "$f"
done
