#!/bin/bash

# Cannot have pipefail because grep will exit with status code 1 if no text is selected
set -eu
IFS=$'\n\t'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
  # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

files=$(exec git diff-index --cached --check $against -- | sed '/^[-+]/d' | cut -d: -f1 | uniq)
for f in $files; do
    # Skip modifying non-text files
    if [ "$(file -bL --mime "$f" | grep '^text')" != "" ]; then
        continue
    fi

    # Remove trailing whitespace
    echo "* Removed whitespace: $f"
    if [[ $(uname) == Darwin ]]; then
        sed -i '' -E 's/[[:space:]]*$//' "$f"
    else
        sed -i 's/[[:space:]]*$//' "$f"
    fi
    git add "$f"
done

files=$(git diff-index --name-status --cached HEAD | grep -v ^D | cut -c3-)
for f in $files; do
    # Skip modifying non-text files
    if [ "$(file -bL --mime "$f" | grep '^text')" == "" ]; then
        continue
    fi

    # Add linebreak to end of file if it doesn't have one
    if [ "$(tail -c 1 "$f")" != "" ]
    then
        echo >> "$f"
    fi
    git add "$f"
done
